name: test
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        version: [1.19.x]
    name: Go ${{ matrix.version }} tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build code
        run: make

      - name: Run tests
        run: make check
  updateReports:
    name: Update reports
    needs: test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Update Go Report Card
        uses: creekorful/goreportcard-action@v1.0
