name: test
on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                include:
                    - job_name: macOS
                      go: 1.19.x
                      os: macOS-latest

                    - job_name: Linux
                      go: 1.19.x
                      os: ubuntu-latest
        name: ${{ matrix.job_name }} Go ${{ matrix.go }}
        runs-on: ${{ matrix.os }}
        steps:
            - name: Set up Go ${{ matrix.go }}
              uses: actions/setup-go@v3
              with:
                  go-version: ${{ matrix.go }}

            - name: Check out code
              uses: actions/checkout@v3

            - name: Build code
              run: make

            - name: Run tests
              run: make check
    update:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Update report card
              uses: creekorful/goreportcard-action@v1.0
